### ISSUE TITLE
Import PHPUnit tests and GitHub Actions setup from coopcycle/vroom-php

### ISSUE THREAD

**Issue by alexsegura** [webstacknl/vroom-php#2]
Hi 👋

It's only when I submitted a similar package (https://github.com/coopcycle/vroom-php) to Packagist, that I realized this one existed

I searched for a PHP client for VROOM when we introduced route optimization, but couldn't find one (at that time)
This package is way more feature complete, so I see no good reason of continuing with `coopcycle/vroom-php`. 

At least, I can contribute some PHPUnit tests, and setup GitHub Actions

**Comment by mwansinck** [comment]
Thanks for your PR, I will review your contributions and test if everything is compatible with our setup, if so I will merge your PR.

**Comment by mwansinck** [comment]
@alexsegura 

I have merged your PR into master and added two commits after that;

Added docblocks and CS improvements 
https://github.com/webstacknl/vroom-php/commit/a38704e4c4151c12e37990f4d356e3dc4ca4b0c5 

Removed instanceOf assert because return type of method could only be a Solution so this test did never fail anyway
https://github.com/webstacknl/vroom-php/commit/0fbc67b270b3b10788f63f15da63c68411f65bd8

Tests run successfully, however I needed to append "tests" after the command (I did copy phpunit.xml.dist to phpunit.xml). 

```
vendor/bin/phpunit tests
PHPUnit 7.5.20 by Sebastian Bergmann and contributors.

...                                                                 3 / 3 (100%)

Time: 373 ms, Memory: 6.00 MB

OK (3 tests, 5 assertions)
```

Could you also create a PR for github actions please?

**Comment by alexsegura** [comment]
@mwansinck cool, thanks for merging my PR 🙂

> I needed to append "tests" after the command

Strange, I don't even need to rename the `phpunit.xml.dist` file for it to work

> Removed instanceOf assert because return type of method could only be a Solution so this test did never fail anyway

Yes sure, the test is not very useful, it was just to introduce the logic of mocking HTTP requests. 
Now we can test more edge cases. 

> Could you also create a PR for github actions please?

Sure, I do this later today

**Comment by mwansinck** [comment]
@alexsegura Just a friendly reminder :-)
