### ISSUE TITLE
Declaration of Serializer::normalizer must be compatible with Symfony serializer::normalize

### ISSUE THREAD

**Issue by thisbar** [webstacknl/vroom-php#7]
Hi,

I am getting this error on PHP 8.1 FPM with Nginx:
Maybe the package.json is allowing to update to a newer version of the serializer that may be incompatible with vroom-php?

`Fatal error: Declaration of Webstack\Vroom\Serializer::normalize($data, $format = null, array $context = []) must be compatible with Symfony\Component\Serializer\Serializer::normalize(mixed $data, ?string $format = null, array $context = []): ArrayObject|array|string|int|float|bool|null in /var/www/rutasBlega/vendor/webstack/vroom-php/src/Serializer.php on line 37`

**Comment by mwansinck** [comment]
I will look into it :-) (instead of package.json I think you are referring to composer.json).

Your issue could not be PHP 8.1 related but seems to be related to the Symfony Serializer.
Could you please add information about which Syfmony version you are using?
You can find this by running the following command `composer info symfony/serializer`

**Comment by mwansinck** [comment]
Hi @thisbar, this should be fixed in https://github.com/webstacknl/vroom-php/releases/tag/v1.3.0.
